### ISSUE TITLE
Tracking Issue for gb!dllvl command

### ISSUE THREAD

**Issue by Voksius** [gmdEzreal/geobrowsr#1]
- [ ] Display level name and author
- [ ] Display level author's player id
- [ ] Display level description (needs to be decoded from base64)
- [ ] Display level password (xor encrypted, more info at gddocs)
- [ ] Display HTTP Response code for debugging
- [ ] Ping the caller of the command

**Comment by Voksius** [comment]
I found a [GDDocs MD file](https://github.com/gd-programming/gddocs/blob/master/docs/topics/level_passwords.md#decoding) that should be able to help you with level password decryption
